// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace MMP_API.Models
{
    public partial class MMP_DevContext : DbContext
    {
        public MMP_DevContext()
        {
        }

        public MMP_DevContext(DbContextOptions<MMP_DevContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Person> Person { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Person>(entity =>
            {
                entity.ToTable("Person", "Info");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.AttachmentId).HasColumnName("AttachmentID");

                entity.Property(e => e.BirthDate).HasColumnType("date");

                entity.Property(e => e.Email).HasMaxLength(50);

                entity.Property(e => e.InsuranceId)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("InsuranceID");

                entity.Property(e => e.LastModificationDate).HasColumnType("datetime");

                entity.Property(e => e.LkJobStatusId).HasColumnName("LK_JobStatusID");

                entity.Property(e => e.MilitaryAttachmentId).HasColumnName("MilitaryAttachmentID");

                entity.Property(e => e.MilitaryServiceId).HasColumnName("MilitaryServiceID");

                entity.Property(e => e.Mobile).HasMaxLength(20);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.NationalityId).HasColumnName("NationalityID");

                entity.Property(e => e.Nid)
                    .IsRequired()
                    .HasMaxLength(14)
                    .HasColumnName("NID");

                entity.Property(e => e.Phone).HasMaxLength(50);

                entity.Property(e => e.PhoneCode).HasMaxLength(50);

                entity.Property(e => e.SocailStatusId).HasColumnName("SocailStatusID");

                entity.Property(e => e.SonofmartyrsAttachmentId).HasColumnName("sonofmartyrsAttachmentID");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}