// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MMP_API.Models
{
    public partial class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Nid { get; set; }
        public string InsuranceId { get; set; }
        public int UserType { get; set; }
        public DateTime BirthDate { get; set; }
        public int? SocailStatusId { get; set; }
        public int? MilitaryServiceId { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string PhoneCode { get; set; }
        public int? NationalityId { get; set; }
        public string Mobile { get; set; }
        public bool? IsHandCap { get; set; }
        public bool? IsOwnCar { get; set; }
        public bool? IsDriverLicense { get; set; }
        public bool? HaveEducation { get; set; }
        public int? LkJobStatusId { get; set; }
        public Guid? AttachmentId { get; set; }
        public DateTime? LastModificationDate { get; set; }
        public int? ModifiedBy { get; set; }
        public Guid? MilitaryAttachmentId { get; set; }
        public bool? Issonofmartyrs { get; set; }
        public Guid? SonofmartyrsAttachmentId { get; set; }
        public bool? HaveHeavyEquipmentLicense { get; set; }
        public bool? WorkFoodBusiness { get; set; }
    }
}